steps:
  - name: Checkout code
  - name: Docker login
  - name: Build image
  - name: Push image

  # 👇 ADD BELOW THIS
  - name: Deploy to EC2
    uses: appleboy/ssh-action@v1.0.0
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ubuntu
      key: ${{ secrets.EC2_KEY }}
      script: |
        cd cloud-project
        ./deploy.sh